M48
; DRILL file {KiCad 8.0.5} date 2024-10-30T11:18:25-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-30T11:18:25-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0512
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X5.0823Y-1.2303
X5.0823Y-1.7815
X5.0823Y-2.2441
T2
X4.7835Y-2.4016
X4.7838Y-1.0335
M30
